### ISSUE TITLE
Nutmeg compatibility

### ISSUE THREAD

**Issue by mrtndwrd** [raccoongang/xblock-video#551]
I took a look at what's needed to be able to run this xblock under Nutmeg.

First of all, the `xblock-utils` dependency needs to be loosened, because Nutmeg ships `xblock-utils==3.0.0`.

Secondly, we'll need a newer version of pycaption. Basically this issue is blocked by https://github.com/pbs/pycaption/issues/293 because all the deps mentioned there are newer in Nutmeg than what pycaption currently allows.

For now, I've fixed my Tutor setup with the following:

1. [Updated xblock-utils dependency](https://github.com/greenhost/xblock-video/commit/be0ab31ed82677586633635d5b208b24a597b3c4)
   - Seems to be fine. Everything still seems to work, but I haven't done rigorous testing yet.
2. Added a Tutor plugin that up/downgrades the other required packages:
 
```yaml
---
name: fix-packages-for-xblock-video
version: 0.1.0
patches:
  openedx-dockerfile-post-git-checkout: |
    # At the time of writing xblock-video is not compatible with these packages
    # as included by Nutmeg, so we need to install older versions of them.
    # These are the latest package versions xblock-video can use:
    # lxml==4.8.0
    # beautifulsoup4==4.10.0
    # cssutils==2.3.1
    # FIXME: This plugin should be temporary, as soon as xblock video supports
    # Nutmeg we should upgrade it and remove this plugin
    RUN sed -i 's|lxml==.*|lxml==4.8.0|' ./requirements/edx/*.txt
    RUN sed -i 's|beautifulsoup4==.*|beautifulsoup4==4.10.0|' ./requirements/edx/*.txt
    RUN sed -i 's|cssutils==.*|cssutils==2.3.1|' ./requirements/edx/*.txt

```
